# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 33974e517399743c2b9a2e62f8497c4b180722759b5fadeda887f866fb9ec38f17a2655e4b44a8d2f0741d95cf2fa98ada276d64e53b565827e36250b7c38b8a

test:
  secret_key_base: 365b2bd2b0cce8892604bbcda7618a95f7bac518de3d3aa5b91d15629a4fb300cd7e753648cd237556fb8b3eb66d20c83cf916d4a81e5575eec662f12182a086

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
